### ISSUE TITLE
błąd po update

### ISSUE THREAD

**Issue by mareczek82** [TowarzyszFatCat/doccli#18]
Hej, 

używałęm doccli na ubuntu, dziś zobaczyłem info o aktualizacji. Wykonałęm ją uzywajac polecenia 

> sudo rm /usr/local/bin/doccli && sudo rm -rf ~/.doccli_src && cd ~ && git clone https://github.com/TowarzyszFatCat/doccli.git && bash doccli/install.sh

niestety wywalało błedem. (nie jestem pewien, nie skopiowałem go ale wydaje mi się, że podobnym co poniżej) 

odinastlowałęm również używając polecenia ze strony, następnie uruchomiłem polecenie do instalacji dodatkowych paczek, potem skrypt instalujący i przy uruchomieniu mam taki komunikat

> marek@Fuji ~> doccli
Exception in thread Thread-1 (start_rpc):
Traceback (most recent call last):
  File "/usr/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/home/marek/.doccli_src/discord_integration.py", line 31, in start_rpc
    RPC.update(activity_type=ActivityType.WATCHING, state=discord_data[1], details=discord_data[0], large_image='icon_1', large_text="Doccli - oglądaj anime bezpośrednio ze swojego terminalu!", buttons=[{"label": "GitHub", "url": "https://github.com/TowarzyszFatCat/doccli"}, {"label": "Discord Projektu", "url": "https://discord.gg/FgfSM7bSEK"}], start=start_time)
  File "/home/marek/.doccli_src/.venv/lib/python3.12/site-packages/pypresence/presence.py", line 36, in update
    self.send_data(1, payload)
  File "/home/marek/.doccli_src/.venv/lib/python3.12/site-packages/pypresence/baseclient.py", line 96, in send_data
Traceback (most recent call last):
  File "/home/marek/.doccli_src/run.py", line 34, in <module>
    assert self.sock_writer is not None, "You must connect your client before sending events!"
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: You must connect your client before sending events!
    m_welcome()
  File "/home/marek/.doccli_src/main_module.py", line 63, in m_welcome
    load()
  File "/home/marek/.doccli_src/main_module.py", line 591, in load
    loaded_data = json.load(json_file)
                  ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

nie jestem zbyt biegły w linuxie, czy pominołem jakiś krok? 

dowód na zainstalowane paczki 

> marek@Fuji ~ [1]> sudo apt install mpv yt-dlp python3-pip python3-venv
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
mpv is already the newest version (0.37.0-1ubuntu4).
yt-dlp is already the newest version (2024.04.09-1).
python3-pip is already the newest version (24.0+dfsg-1ubuntu1).
python3-venv is already the newest version (3.12.3-0ubuntu2).
0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.

**Comment by TowarzyszFatCat** [comment]
Pokaż zawartość folderu z configami. `ls -la ~/.config/doccli/`

**Comment by TowarzyszFatCat** [comment]
W razie wystąpienia tego błędu lub podobnego, należy usunąć `history.json` z `~/.config/doccli/`

**Comment by mareczek82** [comment]
potwierdzam, usunięcie tego pliku pomogło. 
Dziękuję.
